# Generated by Django 4.2.7 on 2023-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_purchaseorder_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='issue_date',
        ),
    ]
